[project]
name = "code-claude"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dummy-Bug", email = "laxyrajput@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.4.0",
    "langchain-openai>=1.6.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
code-claude = "code_claude:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
